### ISSUE TITLE
Duplicate notes

### ISSUE THREAD

**Issue by yajo** [abdon-gadgets/merge-jwl#5]
After restoring from a merge, some notes appeared duplicated in the app.

Deleting one of them deleted both 😕

**Comment by temporarium** [comment]
You may be interested in a similar project here: https://gitlab.com/erykj/jwlmanager
Multi-platform and GUI

**Comment by abdon-copper** [comment]
Sorry for the late reply. I have also experienced this issue were notes get duplicated, but did not yet took the time to investigate.

**Comment by JacobMA360** [comment]
Experienced same problem. Would love to see this issue fixed! 😊

**Comment by abdon-copper** [comment]
This test version was just released: <https://62757e5ac9c06d387430e6b0--merge-jwl.netlify.app/>. It fixed the problem for me. Could someone else also try that URL to see if it works well?

**Comment by JacobMA360** [comment]
@abdon-copper yeah, it worked for me too!👌 It even cleaned up the old notes! Thanks a lot for your work👍👍👍

**Comment by abdon-copper** [comment]
Thanks for your reply Jacob.

Fixed in #6
